/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel.management.system;

import dao.HostelDao;
import javax.swing.JOptionPane;
import model.Hostel;

/**
 *
 * @author test
 */
public class HostelADD extends javax.swing.JFrame {

    /**
     * Creates new form HostelADD
     */
    public HostelADD() {
        initComponents();
        btnSave.setEnabled(false);
        
    }
    
    public void validateFields() {
        String hostelidtxt = txtHostelID.getText();
        String hostelnametxt = txtHostelName.getText();
        String noofroomstxt = txtnoofrooms.getText();
        String noofstudents = txtnoofstudents.getText();

        if (!hostelidtxt.isEmpty() && !hostelnametxt.isEmpty() && !noofroomstxt.isEmpty() && !noofstudents.isEmpty()) {
            btnSave.setEnabled(true);
        } else {
            btnSave.setEnabled(false);
        }
    }

    public void clear(){
        txtHostelID.setText("");
        txtHostelName.setText("");
        txtnoofrooms.setText("");
        txtnoofstudents.setText("");
        btnSave.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHostelID = new javax.swing.JTextField();
        txtHostelName = new javax.swing.JTextField();
        txtnoofrooms = new javax.swing.JTextField();
        txtnoofstudents = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD HOSTEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hostel ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hosel Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number Of Rooms");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number Of Students");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        txtHostelID.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtHostelID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHostelIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtHostelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 230, -1));

        txtHostelName.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtHostelName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHostelNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtHostelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 230, -1));

        txtnoofrooms.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtnoofrooms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnoofroomsKeyReleased(evt);
            }
        });
        getContentPane().add(txtnoofrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 230, -1));

        txtnoofstudents.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtnoofstudents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnoofstudentsKeyReleased(evt);
            }
        });
        getContentPane().add(txtnoofstudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 230, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Fields are valid, proceed with saving
        String hostelID = txtHostelID.getText();
        String hostelName = txtHostelName.getText();
        String noOfRooms = txtnoofrooms.getText();
        String noOfStudents = txtnoofstudents.getText();

        // Create a Hostel object
        Hostel hostel = new Hostel();
        hostel.setHostel_ID(hostelID);
        hostel.setHostel_name(hostelName);
        hostel.setNo_of_rooms(noOfRooms);
        hostel.setNo_of_students(noOfStudents);

        // Save the Hostel object to the database
        HostelDao.save(hostel);

        // Clear the text fields if needed
        txtHostelID.setText("");
        txtHostelName.setText("");
        txtnoofrooms.setText("");
        txtnoofstudents.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtHostelIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostelIDKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtHostelIDKeyReleased

    private void txtHostelNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostelNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtHostelNameKeyReleased

    private void txtnoofroomsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoofroomsKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtnoofroomsKeyReleased

    private void txtnoofstudentsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoofstudentsKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtnoofstudentsKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do You Really Want To Close Application","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    // Create an instance of HomeAdminFrame
    HomeAdminFrame adminHome = new HomeAdminFrame();
    
    // Display the HomeAdminFrame
    adminHome.setVisible(true);
    
    // Close the current frame if needed
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostelADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostelADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostelADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostelADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostelADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtHostelID;
    private javax.swing.JTextField txtHostelName;
    private javax.swing.JTextField txtnoofrooms;
    private javax.swing.JTextField txtnoofstudents;
    // End of variables declaration//GEN-END:variables
}
