/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostel.management.system;

import dao.VisitorDao;
import javax.swing.JOptionPane;
import model.Visitor;

/**
 *
 * @author test
 */
public class VisitorADD extends javax.swing.JFrame {

    /**
     * Creates new form VisitorsADD
     */
    public VisitorADD() {
        initComponents();
        btnSave.setEnabled(false);        
    }
    
public void validateFields() {
    String visitorIDTxt = txtvisitorid.getText();
    String inTimeTxt = txtintime.getText();
    String outTimeTxt = txtouttime.getText();
    String dateTxt = txtdate.getText();
    String visitorNameTxt = txtvisitorname.getText();
    String studentIDTxt = txtstudentid.getText();

    if (!visitorIDTxt.isEmpty() && !inTimeTxt.isEmpty() && !outTimeTxt.isEmpty() &&
        !dateTxt.isEmpty() && !visitorNameTxt.isEmpty() && !studentIDTxt.isEmpty()) {
        btnSave.setEnabled(true);
    } else {
        btnSave.setEnabled(false);
    }
}



public void clear() {
    txtvisitorid.setText("");
    txtintime.setText("");
    txtouttime.setText("");
    txtdate.setText("");
    txtvisitorname.setText("");
    txtstudentid.setText("");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtvisitorid = new javax.swing.JTextField();
        txtintime = new javax.swing.JTextField();
        txtouttime = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtvisitorname = new javax.swing.JTextField();
        txtstudentid = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Visitors");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 71, -1, -1));

        jLabel2.setText("Visitor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 178, -1, -1));

        jLabel3.setText("In time");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 234, -1, -1));

        jLabel4.setText("Out time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 289, -1, -1));

        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 339, -1, -1));

        jLabel6.setText("Visitor Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 390, -1, -1));

        jLabel7.setText("Student ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 437, -1, -1));

        txtvisitorid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvisitoridKeyReleased(evt);
            }
        });
        getContentPane().add(txtvisitorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 175, 71, -1));

        txtintime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtintimeKeyReleased(evt);
            }
        });
        getContentPane().add(txtintime, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 231, 71, -1));

        txtouttime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtouttimeKeyReleased(evt);
            }
        });
        getContentPane().add(txtouttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 286, 71, -1));

        txtdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdateKeyReleased(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 336, 71, -1));

        txtvisitorname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvisitornameKeyReleased(evt);
            }
        });
        getContentPane().add(txtvisitorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 387, 71, -1));

        txtstudentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstudentidKeyReleased(evt);
            }
        });
        getContentPane().add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 434, 71, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 497, -1, -1));

        jButton2.setText("Clear");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 314, -1, -1));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 49, -1, -1));

        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 49, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Fields are valid, proceed with saving
        String visitorID = txtvisitorid.getText();
        String inTime = txtintime.getText();
        String outTime = txtouttime.getText();
        String date = txtdate.getText();
        String visitorName = txtvisitorname.getText();
        String studentID = txtstudentid.getText();

        // Create a Visitor object
        Visitor visitor = new Visitor();
        visitor.setVisitor_ID(visitorID);
        visitor.setIn_time(inTime);
        visitor.setOut_time(outTime);
        visitor.setDate(date);
        visitor.setVisitor_name(visitorName);
        visitor.setStudent_ID(studentID);

        // Save the Visitor object to the database
        VisitorDao.save(visitor);

        // Clear the text fields if needed
        txtvisitorid.setText("");
        txtintime.setText("");
        txtouttime.setText("");
        txtdate.setText("");
        txtvisitorname.setText("");
        txtstudentid.setText("");     
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do You Really Want To Close Application","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        // Create an instance of HomeAdminFrame
        HomeAdminFrame adminHome = new HomeAdminFrame();

        // Display the HomeAdminFrame
        adminHome.setVisible(true);

        // Close the current frame if needed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtvisitoridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvisitoridKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtvisitoridKeyReleased

    private void txtintimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtintimeKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtintimeKeyReleased

    private void txtouttimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtouttimeKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtouttimeKeyReleased

    private void txtdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtdateKeyReleased

    private void txtvisitornameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvisitornameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtvisitornameKeyReleased

    private void txtstudentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstudentidKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtstudentidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitorADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitorADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitorADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitorADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitorADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtintime;
    private javax.swing.JTextField txtouttime;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtvisitorid;
    private javax.swing.JTextField txtvisitorname;
    // End of variables declaration//GEN-END:variables
}
